== Indexer des documents

Avant de pouvoir des recherches dans notre jeu de données, nous devons bien evidemment indexer nos premiers documents.
Pour cela, Elasticsearch nous propose une API, proche des API REST, nous permettant de créer, lire, modifier ou encore
supprimer un ou des documents.

Nous allons aborder dans ce chapitre ces APIs, et également celle permettant de faire des indexation en masse de manière
performante.

=== Structure de l'API

Les documents que nous souhaitons indexer dans Elasticsearch seront placés dans un index. Vous êtes en charge de définir
le nom de cet index. Une fois ce nom défini, nous allons utiliser dans les différentes requêtes HTTP que nous allons utiliser.

Voici la liste des APIs que nous allons utiliser pour indexer une document dans un index *products* :

* Pour une première indexation :

[source]
----
POST /products/_doc
{ ... }
----

* Pour une mise à jour totale :

[source]
----
PUT /products/_doc/{id}
{ ... }
----

* Pour la récupération d'un document déjà indexé

[source]
----
GET /products/_doc/{id}
----

* Pour la suppression d'un document déjà indexé

[source]
----
DELETE /products/_doc/{id}
----

=== Bulk API

Lorsque nous souhaitons indexer, mettre à jour ou encore supprimer de multiples documents, nous pourrions bien évidemment faire une requête HTTP par document à traiter. Mais cela ne serait pas optimal. Elasticsearch propose l'API bill permettant de faire, en une seule requête, plusieurs actions dans Elasticsearch

Pour ce faire, nous allons utiliser le endpoints _bulk et un corp de requête au formation ND JSON (New Line délimited JSON). Ce format ressemble à du JSON, mais ne l'est pas vraiment. En effet, chaque ligne est un document JSON valide, mais l'ensemble du corps de n'est pas.

Dans ce corps de requête, une action sera définie sur une ligne (pour les actions de suppression de document par exemple) ou sur deux lignes (pour les actions de mises à jour ou création). Pour ce dernier cas, la premiere correspondra à l'action souhaitée. Et là deuxième ligne, au document a indexer.

 Les différents actions supportées sont :

- index : création ou mise à jour
- create : creation
- update : mise à jour
- delete : suppression.

Dans l'exemple ci-dessois, en une seule requête nous exécutons les 4 actions définies précédemment.

[source]
----
POST _bulk
{ "index" : { "_index" : "test", "_id" : "1" } }
{ "field1" : "value1" }
{ "delete" : { "_index" : "test", "_id" : "2" } }
{ "create" : { "_index" : "test", "_id" : "3" } }
{ "field1" : "value3" }
{ "update" : {"_id" : "1", "_index" : "test"} }
{ "doc" : {"field2" : "value2"} }
----
